#!/usr/bin/env python3
"""
Process badapple.mp4 to generate Rust code for frame-by-frame rendering
with double buffering optimization.
"""

import subprocess
import os
import sys
from PIL import Image
import shutil
import mido

# Configuration
VIDEO_FILE = "badapple.mp4"
MIDI_FILE = "../midi/examples/badapple.mid"
TARGET_WIDTH = 100
TARGET_HEIGHT = 75
TARGET_FPS = 8  # Target frames per second
TEMP_FOLDER = "/tmp/badapple_frames"  # tmpfs
OUTPUT_FILE = "src/badapple.rs"
MAX_FRAMES = 500  # For testing, process only first 50 frames

def ensure_temp_folder():
    """Create temp folder if it doesn't exist, clean it if it does."""
    if os.path.exists(TEMP_FOLDER):
        shutil.rmtree(TEMP_FOLDER)
    os.makedirs(TEMP_FOLDER)
    print(f"Created temp folder: {TEMP_FOLDER}")

def extract_frames():
    """Extract frames from video using ffmpeg, rescaling to target dimensions."""
    print(f"Extracting frames from {VIDEO_FILE}...")
    
    # Use ffmpeg to extract frames, rescale, and convert to grayscale
    cmd = [
        "ffmpeg",
        "-i", VIDEO_FILE,
        "-vf", f"fps={TARGET_FPS},scale={TARGET_WIDTH}:{TARGET_HEIGHT}:flags=lanczos,format=gray",
        "-frames:v", str(MAX_FRAMES),
        os.path.join(TEMP_FOLDER, "frame_%04d.png")
    ]
    
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"Error running ffmpeg: {result.stderr}")
        sys.exit(1)
    
    print(f"Extracted {MAX_FRAMES} frames successfully")

def load_frame(frame_num):
    """Load a frame and convert to binary (black/white) pixels."""
    filename = os.path.join(TEMP_FOLDER, f"frame_{frame_num:04d}.png")
    img = Image.open(filename).convert('L')  # Convert to grayscale
    
    # Convert to binary: threshold at 128
    pixels = []
    for y in range(img.height):
        row = []
        for x in range(img.width):
            pixel = img.getpixel((x, y))
            # 0 = black, 1 = white
            row.append(1 if pixel > 128 else 0)
        pixels.append(row)
    
    return pixels

def get_pixel_diff(frame1, frame2):
    """Get list of pixels that differ between two frames."""
    diff = []
    for y in range(len(frame1)):
        for x in range(len(frame1[0])):
            if frame1[y][x] != frame2[y][x]:
                diff.append((x, y, frame2[y][x]))
    return diff

def load_midi():
    """Load and process MIDI file, converting to frame-based events."""
    print(f"Loading MIDI file: {MIDI_FILE}")
    
    if not os.path.exists(MIDI_FILE):
        print(f"Warning: MIDI file not found: {MIDI_FILE}")
        return []
    
    mid = mido.MidiFile(MIDI_FILE)
    
    # Calculate ticks per frame
    frame_duration = 1.0 / TARGET_FPS  # seconds per frame
    
    # Collect all events with absolute time in seconds
    events = []
    for track_num, track in enumerate(mid.tracks):
        print(f"  Track {track_num}: {track.name}")
        current_time = 0.0
        
        for msg in track:
            current_time += mido.tick2second(msg.time, mid.ticks_per_beat, 500000)
            
            if msg.type == 'note_on' and msg.velocity > 0:
                events.append({
                    'time': current_time,
                    'type': 'note_on',
                    'note': msg.note,
                    'velocity': msg.velocity,
                    'track': track_num
                })
            elif msg.type == 'note_off' or (msg.type == 'note_on' and msg.velocity == 0):
                events.append({
                    'time': current_time,
                    'type': 'note_off',
                    'note': msg.note,
                    'track': track_num
                })
            elif msg.type == 'program_change':
                events.append({
                    'time': current_time,
                    'type': 'program_change',
                    'program': msg.program,
                    'track': track_num
                })
            elif msg.type == 'set_tempo':
                # Update tempo for future conversions (simplified)
                pass
    
    # Sort events by time
    events.sort(key=lambda e: e['time'])
    
    # Convert to frame-based events
    frame_events = [[] for _ in range(MAX_FRAMES)]
    
    for event in events:
        frame_num = int(event['time'] / frame_duration)
        if 0 <= frame_num < MAX_FRAMES:
            frame_events[frame_num].append(event)
    
    print(f"  Loaded {len(events)} MIDI events across {MAX_FRAMES} frames")
    
    return frame_events

def generate_rust_code():
    """Generate the Rust code for all frames."""
    print("Generating Rust code...")
    
    lines = []
    
    # Load MIDI events
    midi_events = load_midi()
    
    # Header
    lines.append("// Auto-generated by process.py")
    lines.append("// Bad Apple frame renderer with double buffering and MIDI playback")
    lines.append("")
    lines.append("use parm::screen::{set_pixel_buf_unchecked, Buffer, ColorEncoded, ColorSimple, set_buf, ParmScreen, Color};")
    lines.append("use parm::embedded_graphics::prelude::*;")
    lines.append("use parm::embedded_graphics::primitives::*;")
    lines.append("use parm::midi::{set_note, set_vol, press_key, release_key, set_instr, MidiNote, MidiInstrument};")
    lines.append("use parm::mmio::TIMER;")
    lines.append("")
    lines.append("#[inline(always)]")
    lines.append("fn timer() -> u32 {")
    lines.append("    TIMER.read()")
    lines.append("}")
    lines.append("")
    lines.append("const W: ColorEncoded = ColorEncoded(0); // White")
    lines.append("const B: ColorEncoded = ColorEncoded(1); // Black")
    lines.append("const B0: Buffer = Buffer::B0;")
    lines.append("const B1: Buffer = Buffer::B1;")
    lines.append("")
    # Calculate frame duration in timer ticks (timer increments 100 times per second)
    frame_duration_ticks = 100 // TARGET_FPS
    lines.append(f"// Target FPS: {TARGET_FPS}, Frame duration: {frame_duration_ticks} timer ticks (timer @ 100Hz)")
    lines.append(f"const FRAME_DURATION: u32 = {frame_duration_ticks};")
    lines.append("")
    
    # Load all frames
    frames = []
    for i in range(1, MAX_FRAMES + 1):
        frames.append(load_frame(i))
        print(f"Loaded frame {i}/{MAX_FRAMES}")
    
    # Create virtual frame 0 (fully black)
    if frames:
        height = len(frames[0])
        width = len(frames[0][0])
        frame0 = [[0 for _ in range(width)] for _ in range(height)]
    
    # Generate frame 0 (virtual frame - fully black)
    lines.append("#[inline(never)]")
    lines.append("pub unsafe fn frame0() {")
    lines.append(f"    let rect = Rectangle::new(Point::new(0, 0), Size::new({width}, {height}));")
    lines.append("    ParmScreen(B0).fill_solid(&rect, Color::Simple(ColorSimple::Black)).ok();")
    lines.append("    ParmScreen(B1).fill_solid(&rect, Color::Simple(ColorSimple::Black)).ok();")
    lines.append("    set_buf(B0);")
    lines.append("    let start_time = timer();")
    lines.append("    frame1(start_time);")
    lines.append("}")
    lines.append("")
    
    # Generate frame functions
    for frame_num in range(1, MAX_FRAMES + 1):
        frame_data = frames[frame_num - 1]
        frame_midi = midi_events[frame_num - 1] if frame_num - 1 < len(midi_events) else []
        
        # Determine which buffer to draw on (alternate starting from frame 1)
        draw_buffer = "B1" if frame_num % 2 == 1 else "B0"
        
        lines.append(f"#[inline(never)]")
        lines.append(f"unsafe fn frame{frame_num}(last_frame_time: u32) {{")
        
        # Process MIDI events for this frame
        if frame_midi:
            lines.append(f"    // MIDI events for frame {frame_num}")
            
            # Count events for logging
            note_offs = [e for e in frame_midi if e['type'] == 'note_off']
            note_ons = [e for e in frame_midi if e['type'] == 'note_on']
            program_changes = [e for e in frame_midi if e['type'] == 'program_change']
            
            if note_ons or note_offs or program_changes:
                print(f"Frame {frame_num}: {len(note_ons)} note_on, {len(note_offs)} note_off, {len(program_changes)} program_change")
            
            # Process all MIDI events in order (they should already be sorted by time)
            for event in frame_midi:
                if event['type'] == 'note_on':
                    note = event['note']
                    velocity = event['velocity']
                    lines.append(f"    set_note(MidiNote::from_byte({note}));")
                    lines.append(f"    set_vol({velocity});")
                    lines.append(f"    press_key();")
                elif event['type'] == 'note_off':
                    note = event['note']
                    lines.append(f"    set_note(MidiNote::from_byte({note}));")
                    lines.append(f"    release_key();")
                elif event['type'] == 'program_change':
                    program = event['program']
                    lines.append(f"    set_instr(MidiInstrument::from_byte({program}));")
            
            lines.append("")
        
        # For frames 1 and 2, compare with frame 0 (fully black)
        if frame_num <= 2:
            diff = get_pixel_diff(frame0, frame_data)
            if not frame_midi:  # Only print if no MIDI events printed
                print(f"Generating frame {frame_num} (diff from frame0, {len(diff)} changes)...")
            for x, y, color_val in diff:
                color = "W" if color_val == 1 else "B"
                lines.append(f"    set_pixel_buf_unchecked({draw_buffer}, {x}, {y}, {color});")
        else:
            # For frames 3+, only draw differences from frame (frame_num - 2)
            # Frame 3 compares to frame 1, frame 4 to frame 2, etc.
            ref_frame_num = frame_num - 2
            ref_frame = frames[ref_frame_num - 1]
            diff = get_pixel_diff(ref_frame, frame_data)
            
            if not frame_midi:  # Only print if no MIDI events printed
                print(f"Generating frame {frame_num} (diff render, {len(diff)} changes)...")
            for x, y, color_val in diff:
                color = "W" if color_val == 1 else "B"
                lines.append(f"    set_pixel_buf_unchecked({draw_buffer}, {x}, {y}, {color});")
        
        # Wait for the right time to show this frame
        lines.append("    // Wait until it's time to show this frame")
        lines.append("    let target_time = last_frame_time + FRAME_DURATION;")
        lines.append("    while timer() < target_time {}")
        lines.append("")
        
        # Switch to this buffer
        lines.append(f"    set_buf({draw_buffer});")
        lines.append("    let current_time = timer();")
        lines.append("")
        
        # Call next frame or halt
        if frame_num < MAX_FRAMES:
            lines.append(f"    frame{frame_num + 1}(current_time);")
        else:
            lines.append("    // Last frame - infinite loop")
            lines.append("    loop {}")
        
        lines.append("}")
        lines.append("")
    
    # Write to file
    with open(OUTPUT_FILE, 'w') as f:
        f.write('\n'.join(lines))
    
    print(f"Generated {OUTPUT_FILE}")

def main():
    print("=" * 60)
    print("Bad Apple Video Processor")
    print("=" * 60)
    
    # Check if video file exists
    if not os.path.exists(VIDEO_FILE):
        print(f"Error: {VIDEO_FILE} not found!")
        sys.exit(1)
    
    # Step 1: Prepare temp folder
    ensure_temp_folder()
    
    # Step 2: Extract frames
    extract_frames()
    
    # Step 3: Generate Rust code
    generate_rust_code()
    
    print("=" * 60)
    print("Done!")
    print("=" * 60)

if __name__ == "__main__":
    main()

