#!/usr/bin/env python3
"""
Process badapple.mp4 to generate Rust code for frame-by-frame rendering
with double buffering optimization.
"""

import subprocess
import os
import sys
from PIL import Image
import shutil

# Configuration
VIDEO_FILE = "badapple.mp4"
TARGET_WIDTH = 100
TARGET_HEIGHT = 75
TARGET_FPS = 15  # Target frames per second
TEMP_FOLDER = "/tmp/badapple_frames"  # tmpfs
OUTPUT_FILE = "src/badapple.rs"
MAX_FRAMES = 500  # For testing, process only first 50 frames

def ensure_temp_folder():
    """Create temp folder if it doesn't exist, clean it if it does."""
    if os.path.exists(TEMP_FOLDER):
        shutil.rmtree(TEMP_FOLDER)
    os.makedirs(TEMP_FOLDER)
    print(f"Created temp folder: {TEMP_FOLDER}")

def extract_frames():
    """Extract frames from video using ffmpeg, rescaling to target dimensions."""
    print(f"Extracting frames from {VIDEO_FILE}...")
    
    # Use ffmpeg to extract frames, rescale, and convert to grayscale
    cmd = [
        "ffmpeg",
        "-i", VIDEO_FILE,
        "-vf", f"fps={TARGET_FPS},scale={TARGET_WIDTH}:{TARGET_HEIGHT}:flags=lanczos,format=gray",
        "-frames:v", str(MAX_FRAMES),
        os.path.join(TEMP_FOLDER, "frame_%04d.png")
    ]
    
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"Error running ffmpeg: {result.stderr}")
        sys.exit(1)
    
    print(f"Extracted {MAX_FRAMES} frames successfully")

def load_frame(frame_num):
    """Load a frame and convert to binary (black/white) pixels."""
    filename = os.path.join(TEMP_FOLDER, f"frame_{frame_num:04d}.png")
    img = Image.open(filename).convert('L')  # Convert to grayscale
    
    # Convert to binary: threshold at 128
    pixels = []
    for y in range(img.height):
        row = []
        for x in range(img.width):
            pixel = img.getpixel((x, y))
            # 0 = black, 1 = white
            row.append(1 if pixel > 128 else 0)
        pixels.append(row)
    
    return pixels

def get_pixel_diff(frame1, frame2):
    """Get list of pixels that differ between two frames."""
    diff = []
    for y in range(len(frame1)):
        for x in range(len(frame1[0])):
            if frame1[y][x] != frame2[y][x]:
                diff.append((x, y, frame2[y][x]))
    return diff

def generate_rust_code():
    """Generate the Rust code for all frames."""
    print("Generating Rust code...")
    
    lines = []
    
    # Header
    lines.append("// Auto-generated by process.py")
    lines.append("// Bad Apple frame renderer with double buffering")
    lines.append("")
    lines.append("use parm::screen::{set_pixel_buf_unchecked, Buffer, ColorEncoded, ColorSimple, set_buf, ParmScreen, Color};")
    lines.append("use parm::embedded_graphics::prelude::*;")
    lines.append("use parm::embedded_graphics::primitives::*;")
    lines.append("fn timer() -> u32 { return parm::mmio::TIMER.read(); }")
    lines.append("")
    lines.append("const W: ColorEncoded = ColorEncoded(0); // White")
    lines.append("const B: ColorEncoded = ColorEncoded(1); // Black")
    lines.append("const B0: Buffer = Buffer::Front;")
    lines.append("const B1: Buffer = Buffer::Back;")
    lines.append("")
    # Calculate frame duration in timer ticks (timer increments 100 times per second)
    frame_duration_ticks = 100 // TARGET_FPS
    lines.append(f"// Target FPS: {TARGET_FPS}, Frame duration: {frame_duration_ticks} timer ticks (timer @ 100Hz)")
    lines.append(f"const FRAME_DURATION: u32 = {frame_duration_ticks};")
    lines.append("")
    
    # Load all frames
    frames = []
    for i in range(1, MAX_FRAMES + 1):
        frames.append(load_frame(i))
        print(f"Loaded frame {i}/{MAX_FRAMES}")
    
    # Create virtual frame 0 (fully black)
    if frames:
        height = len(frames[0])
        width = len(frames[0][0])
        frame0 = [[0 for _ in range(width)] for _ in range(height)]
    
    # Generate frame 0 (virtual frame - fully black)
    lines.append("#[inline(never)]")
    lines.append("pub unsafe fn frame0() {")
    lines.append(f"    let rect = Rectangle::new(Point::new(0, 0), Size::new({width}, {height}));")
    lines.append("    ParmScreen::<B0>.fill_solid(&rect, Color::Simple(ColorSimple::Black)).ok();")
    lines.append("    ParmScreen::<B1>.fill_solid(&rect, Color::Simple(ColorSimple::Black)).ok();")
    lines.append("    set_buf(B0);")
    lines.append("    let start_time = timer();")
    lines.append("    frame1(start_time);")
    lines.append("}")
    lines.append("")
    
    # Generate frame functions
    for frame_num in range(1, MAX_FRAMES + 1):
        frame_data = frames[frame_num - 1]
        
        # Determine which buffer to draw on (alternate starting from frame 1)
        draw_buffer = "B1" if frame_num % 2 == 1 else "B0"
        
        lines.append(f"#[inline(never)]")
        lines.append(f"unsafe fn frame{frame_num}(last_frame_time: u32) {{")
        
        # For frames 1 and 2, compare with frame 0 (fully black)
        if frame_num <= 2:
            diff = get_pixel_diff(frame0, frame_data)
            print(f"Generating frame {frame_num} (diff from frame0, {len(diff)} changes)...")
            for x, y, color_val in diff:
                color = "W" if color_val == 1 else "B"
                lines.append(f"    set_pixel_buf_unchecked({draw_buffer}, {x}, {y}, {color});")
        else:
            # For frames 3+, only draw differences from frame (frame_num - 2)
            # Frame 3 compares to frame 1, frame 4 to frame 2, etc.
            ref_frame_num = frame_num - 2
            ref_frame = frames[ref_frame_num - 1]
            diff = get_pixel_diff(ref_frame, frame_data)
            
            print(f"Generating frame {frame_num} (diff render, {len(diff)} changes)...")
            for x, y, color_val in diff:
                color = "W" if color_val == 1 else "B"
                lines.append(f"    set_pixel_buf_unchecked({draw_buffer}, {x}, {y}, {color});")
        
        # Wait for the right time to show this frame
        lines.append("    // Wait until it's time to show this frame")
        lines.append("    let target_time = last_frame_time + FRAME_DURATION;")
        lines.append("    while timer() < target_time {}")
        lines.append("")
        
        # Switch to this buffer
        lines.append(f"    set_buf({draw_buffer});")
        lines.append("    let current_time = timer();")
        lines.append("")
        
        # Call next frame or halt
        if frame_num < MAX_FRAMES:
            lines.append(f"    frame{frame_num + 1}(current_time);")
        else:
            lines.append("    // Last frame - infinite loop")
            lines.append("    loop {}")
        
        lines.append("}")
        lines.append("")
    
    # Write to file
    with open(OUTPUT_FILE, 'w') as f:
        f.write('\n'.join(lines))
    
    print(f"Generated {OUTPUT_FILE}")

def main():
    print("=" * 60)
    print("Bad Apple Video Processor")
    print("=" * 60)
    
    # Check if video file exists
    if not os.path.exists(VIDEO_FILE):
        print(f"Error: {VIDEO_FILE} not found!")
        sys.exit(1)
    
    # Step 1: Prepare temp folder
    ensure_temp_folder()
    
    # Step 2: Extract frames
    extract_frames()
    
    # Step 3: Generate Rust code
    generate_rust_code()
    
    print("=" * 60)
    print("Done!")
    print("=" * 60)

if __name__ == "__main__":
    main()

