[package]
name = "parm"
version = "0.1.0"
edition = "2024"

[dependencies]
hashbrown = { version = "0.16"}
indexmap = { version = "2.10.0", default-features = false }
embedded-graphics = { version = "0.8.1", optional = true, features = ["fixed_point"] }
embedded-io = { version = "0.6", features = ["alloc"] }
rand_core = "0.6.3"
getrandom = { version = "0.2.16", default-features = false, features = ["custom"] }
log = "0.4.28"

[lib]
test = false

[features]
default = []
embedded-graphics = ["dep:embedded-graphics"]
