[workspace]
resolver = "3"
members = ["apps/ball", "apps/basic", "apps/c","apps/calckeyb", "apps/clock", "apps/helloworld", "apps/midi", "apps/netclient", "apps/plotter", "apps/scheme", "apps/scratch", "apps/telnet_text", "apps/telnet_video", "apps/testfp", "apps/webserver","parm"]

[workspace.package]
edition = "2024"

[workspace.dependencies]
parm = { path = "parm" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = 3
lto = "fat"

[patch.crates-io]
ring = { git = "https://github.com/betrusted-io/ring-xous" }
