[package]
name = "test"
version = "0.1.0"
edition = "2021"

[dependencies]
aligned-vec = { version = "0.6.4", default-features = false }
arbitrary-int = "1.3.0"
const_for = "0.1.5"
derive_more = { version = "2.0.1", default-features = false, features = ["full"] }
hashbrown = { version = "0.15.4"}
indexmap = { version = "2.10.0", default-features = false }
indoc = "2.0.6"
paste = "1.0.9"
strum = { version = "0.27.2", default-features = false, features = ["derive"] }
#approx = { version = "0.5.1", default-features = false }
#nalgebra = { version = "0.31.0", default-features = false, features = ["macros", "nalgebra-macros"] }
#num-traits = { version = "0.2.15", default-features = false }
#simba = { version = "0.7.1", default-features = false }

[[bin]]
name = "calculator"
path = "src/calculator.rs"

[[bin]]
name = "calckeyb"
path = "src/calckeyb.rs"

[[bin]]
name = "testfp"
path = "src/testfp.rs"

[[bin]]
name = "testrgb"
path = "src/testrgb.rs"

[[bin]]
name = "testdyn"
path = "src/testdyn.rs"

[[bin]]
name = "basic"
path = "src/basic.rs"

[[bin]]
name = "plotter"
path = "src/plotter.rs"

[[bin]]
name = "parmweb"
path = "src/parmweb.rs"

[[bin]]
name = "telnet_video"
path = "src/telnet_video.rs"

[[bin]]
name = "simpletelnet"
path = "src/simpletelnet.rs"

[[bin]]
name = "lisp"
path = "src/lisprepl.rs"

[[bin]]
name = "ball"
path = "src/ball.rs"

[[bin]]
name = "midi"
path = "src/midi.rs"

[[bin]]
name = "c"
path = "src/crepl.rs"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = 3
lto = "fat"